### ISSUE TITLE
I get error: Table 'redmine.admin_monitor_alerts' doesn't exist

### ISSUE THREAD

**Issue by marvelousvts** [jongha/redmine_sticky_messages#4]
I get the following error.

Processing by AdminMonitorAlertsController#index as HTML
  Parameters: {"conditions"=>"false"}
  Current user: admin (id=1)
Mysql2::Error: Table 'redmine.admin_monitor_alerts' doesn't exist: SHOW FULL FIELDS FROM `admin_monitor_alerts`
Completed 500 Internal Server Error in 14ms

Can you help me to fix it?

**Comment by jongha** [comment]
Hi, @marvelousvts 

It seems other plugin that use the "admin_monitor_alerts" table in your redmine system is installed. 
Perhaps this issue is associated with the admin_monitor_alerts plugin. Please, remove the plugin(or fixed it) and try again. Thanks.
